# Переключение панелей через Alt + стрелки (без префикса)
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Включить поддержку мыши (чтобы просто кликать в нужный терминал)
set -g mouse on
set -g mode-keys vi
