git:
  pagers:
    - colorArg: always
      pager: delta --paging=never --side-by-side
os:
  editPreset: 'nvim'
  edit: "if [ -n \"$NVIM\" ]; then nvim --server $NVIM --remote-send '<C-\\><C-n><cmd>close<cr>' && nvim --server $NVIM --remote {{filename}}; else nvim {{filename}}; fi"
  editInTerminal: true 
