[colors.primary]
foreground = "#a9b7c6"
background = "#262626"

[colors.cursor]
cursor = "#a9b7c6"
text = "#2b2b2b"

[colors.selection]
text = "#2b2b2b"
background = "#214283"

[colors.normal]
black =   "#000000"
red =     "#ff6b68"
green =   "#a8c023"
yellow =  "#dcae58"
blue =    "#3971ed"
magenta = "#a36ac7"
cyan =    "#4cb5b5"
white =   "#cfcfc2"

[colors.bright]
black =   "#7f7f7f"
red =     "#ff6b68"
green =   "#a8c023"
yellow =  "#dcae58"
blue =    "#3971ed"
magenta = "#a36ac7"
cyan =    "#4cb5b5"
white =   "#ffffff"
