enable_audio_bell no

background            #242424
foreground            #a9b7c6
cursor                #bbbbbb
selection_background  #214283
selection_foreground  #a9b7c6

# Black
color0  #000000
color8  #555555
# Red
color1  #4e0e0e
color9  #ff4e4e
# Green
color2  #3a731d
color10 #7bc342
# Yellow
color3  #a78300
color11 #f9c73b
# Blue
color4  #244081
color12 #4d7cc7
# Magenta
color5  #5c1d68
color13 #b746c7
# Cyan
color6  #006c6c
color14 #009393
# White
color7  #bbbbbb
color15 #ffffff
